<?php
declare(strict_types=1);

/**
 * English translations. Keys are the Arabic source strings used across the
 * app — a missing key simply falls back to Arabic, so keep this in sync when
 * adding UI text (grep: __(' ).
 */

return [
    // Navigation & layout
    'اللوجات'                => 'Logs',
    'تنظيف'                  => 'Cleanup',
    'سجل النشاط'             => 'Activity log',
    'سجل نشاطي'              => 'My activity log',
    'سجل نشاط اللوحة'        => 'Dashboard activity log',
    'الإعدادات'              => 'Settings',
    'المستخدمون'             => 'Users',
    'خروج'                   => 'Log out',
    'حسابي'                  => 'My account',
    'تبديل الوضع الفاتح/الداكن' => 'Toggle light/dark mode',
    'تبديل اللغة'            => 'Switch language',
    'لوحة إدارة اللوجات'     => 'Log management dashboard',
    'لوحة اللوجات'           => 'Log dashboard',
    'لوحة إدارة ومتابعة اللوجات' => 'Log management & monitoring dashboard',

    // Auth
    'تسجيل الدخول'           => 'Sign in',
    'دخول'                   => 'Sign in',
    'اسم المستخدم'           => 'Username',
    'كلمة المرور'            => 'Password',
    'تم إيقاف المحاولات مؤقتًا بعد عدة محاولات فاشلة. حاول بعد قليل.' => 'Sign-in temporarily locked after several failed attempts. Try again shortly.',
    'اسم المستخدم أو كلمة المرور غير صحيحة.' => 'Incorrect username or password.',
    'مرحبًا'                 => 'Welcome',
    'هذه الصفحة متاحة للمديرين فقط.' => 'This page is for administrators only.',

    // First-run setup
    'الإعداد الأول'          => 'First-run setup',
    'أنشئ حساب المدير الأول للوحة التحكم' => 'Create the first administrator account',
    '3-32 حرفًا: حروف إنجليزية، أرقام، والرموز . _ -' => '3-32 characters: letters, digits, and . _ -',
    '8 أحرف على الأقل'       => 'At least 8 characters',
    'تأكيد كلمة المرور'      => 'Confirm password',
    'إنشاء الحساب'           => 'Create account',
    'كلمتا المرور غير متطابقتين.' => 'The passwords do not match.',

    // Users & roles
    'مدير'                   => 'Admin',
    'مشاهدة فقط'             => 'View only',
    'الصلاحية'               => 'Role',
    'حساب على اللوحة.'       => 'account(s) on this dashboard.',
    'إضافة مستخدم'           => 'Add user',
    'إضافة'                  => 'Add',
    'يحذف اللوجات، يغيّر الإعدادات، ويدير المستخدمين ويرى سجل الجميع.' => 'deletes logs, changes settings, manages users, and sees everyone\'s activity.',
    'يعرض ويحمّل اللوجات، ويرى سجل نشاطه هو فقط.' => 'views and downloads logs, and sees only their own activity.',
    'أنت'                    => 'you',
    'أُنشئ'                  => 'Created',
    'آخر دخول'               => 'Last login',
    'كلمة مرور'              => 'Password',
    'كلمة مرور جديدة'        => 'New password',
    'تغيير'                  => 'Change',
    'حذف'                    => 'Delete',
    'حذف المستخدم'           => 'Delete user',
    'حذف المستخدم %s؟'       => 'Delete user %s?',
    'اسم المستخدم يجب أن يكون 3-32 حرفًا (حروف إنجليزية، أرقام، . _ -).' => 'Username must be 3-32 characters (letters, digits, . _ -).',
    'كلمة المرور يجب أن تكون 8 أحرف على الأقل.' => 'Password must be at least 8 characters.',
    'صلاحية غير معروفة.'     => 'Unknown role.',
    'اسم المستخدم موجود بالفعل.' => 'Username already exists.',
    'تعذّر حفظ ملف المستخدمين.' => 'Could not save the users file.',
    'تم إنشاء المستخدم.'     => 'User created.',
    'المستخدم غير موجود.'    => 'User not found.',
    'لا يمكن حذف آخر مدير في النظام.' => 'The last administrator cannot be deleted.',
    'تم حذف المستخدم.'       => 'User deleted.',
    'تم تغيير كلمة المرور.'  => 'Password changed.',
    'لا بد من وجود مدير واحد على الأقل.' => 'At least one administrator is required.',
    'تم تحديث الصلاحية.'     => 'Role updated.',
    'لا يمكنك حذف حسابك الحالي.' => 'You cannot delete your own account.',
    'لا يمكنك تغيير صلاحية حسابك الحالي.' => 'You cannot change your own role.',

    // Account
    'تغيير كلمة المرور'      => 'Change password',
    'كلمة المرور الحالية'    => 'Current password',
    'كلمة المرور الجديدة'    => 'New password',
    'تأكيد كلمة المرور الجديدة' => 'Confirm new password',
    'تحديث'                  => 'Update',
    'عرض سجل نشاطي'          => 'View my activity log',
    'كلمة المرور الحالية غير صحيحة.' => 'Current password is incorrect.',
    'كلمتا المرور الجديدتان غير متطابقتين.' => 'The new passwords do not match.',

    // Dashboard
    'إدارة المسارات'         => 'Manage paths',
    'لا يوجد مسار لوجات صالح' => 'No valid log path',
    'اذهب إلى الإعدادات'     => 'Go to settings',
    'اطلب من المدير ضبط المسار.' => 'Ask an administrator to configure the path.',
    'القائمة غير كاملة — تم تخطي' => 'Listing incomplete — skipped',
    'مجلد لعدم وجود صلاحية قراءة:' => 'folder(s) with no read permission:',
    'عدد الملفات'            => 'Files',
    'الحجم الكلي'            => 'Total size',
    'أقدم ملف'               => 'Oldest file',
    'أحدث تعديل'             => 'Latest change',
    'ابحث باسم الملف أو المجلد…' => 'Search by file or folder name…',
    'أقدم من'                => 'Older than',
    'يوم'                    => 'day(s)',
    'تاريخ التعديل'          => 'Modified date',
    'الحجم'                  => 'Size',
    'الاسم'                  => 'Name',
    'تنازلي'                 => 'Descending',
    'تصاعدي'                 => 'Ascending',
    'تطبيق'                  => 'Apply',
    'مسح الفلتر'             => 'Clear filter',
    'لا توجد ملفات مطابقة'   => 'No matching files',
    'جرّب تعديل الفلتر، أو راجع أنماط الملفات في الإعدادات.' => 'Try adjusting the filter, or review the file patterns in settings.',
    'سيتم حذف %s ملف نهائيًا. هل أنت متأكد؟' => '%s file(s) will be permanently deleted. Are you sure?',
    'ملف مختار'              => 'file(s) selected',
    'حذف المختار'            => 'Delete selected',
    'إلغاء التحديد'          => 'Clear selection',
    'تحديد الكل'             => 'Select all',
    'الملف'                  => 'File',
    'آخر تعديل'              => 'Last modified',
    'العمر'                  => 'Age',
    'إجراءات'                => 'Actions',
    'لا توجد صلاحية حذف'     => 'No delete permission',
    'عرض'                    => 'View',
    'تحليل'                  => 'Analyze',
    'تحميل'                  => 'Download',
    'منذ'                    => '',
    'من حذف ماذا'            => 'Who deleted what',
    'كل السجل'               => 'Full log',
    'ملف'                    => 'file(s)',
    'عملية'                  => 'operation(s)',
    'آخرها منذ'              => 'last one',
    'آخر النشاطات'           => 'Recent activity',
    'عرض الكل'               => 'View all',
    'لم تختر أي ملف.'        => 'No files selected.',
    'تم حذف %d ملف (%s).'    => 'Deleted %d file(s) (%s).',
    'فشل حذف %d ملف: %s'     => 'Failed to delete %d file(s): %s',

    // Time (ago)
    'الآن'                   => 'just now',
    'دقيقة'                  => 'min ago',
    'ساعة'                   => 'hr ago',
    'شهر'                    => 'month(s)',
    'سنة'                    => 'year(s)',

    // View log
    'آخر'                    => 'Last',
    'سطر'                    => 'line(s)',
    'تلوين نص داخل اللوج…'   => 'Highlight text in the log…',
    'الملف فارغ'             => 'File is empty',
    'الملف أكبر من %d ميجابايت — يتم عرض آخر أسطر فقط. حمّل الملف لمراجعته كاملًا.' => 'File is larger than %d MB — only the last lines are shown. Download it to review in full.',
    'معروض آخر %d سطر فقط من الملف.' => 'Showing only the last %d lines of the file.',
    'رجوع'                   => 'Back',
    'الملف غير موجود أو غير مسموح بالوصول إليه.' => 'File not found or access denied.',
    'الملف غير موجود.'       => 'File not found.',

    // Analyze
    'الأكثر تكرارًا'         => 'Top repeats',
    'عرض اللوج'              => 'View log',
    'السطور المتشابهة بتتجمّع مع بعض حتى لو التاريخ أو الأرقام أو الـ IP جواها مختلفين.' => 'Similar lines are grouped together even when the timestamps, numbers, or IPs inside them differ.',
    'الملف كبير'             => 'Large file',
    'تم تحليل'               => 'analyzed the',
    'فقط (الأحدث).'          => 'only (the most recent).',
    'وسّع النافذة:'          => 'Widen the window:',
    'إجمالي السطور'          => 'Total lines',
    'رسائل مختلفة (بعد التجميع)' => 'Distinct messages (after grouping)',
    'أكثر رسالة تكرارًا'     => 'Most repeated message',
    'مرة'                    => 'times',
    'أكثر الأخطاء تكرارًا'   => 'Most repeated errors',
    'أكثر السطور تكرارًا (كل الأنواع)' => 'Most repeated lines (all levels)',
    'لا توجد سطور أخطاء في الملف' => 'No error lines in this file',
    'التكرار'                => 'Count',
    'النسبة'                 => 'Share',
    'النوع'                  => 'Level',
    'نموذج السطر'            => 'Sample line',
    'أول ظهور'               => 'First seen',
    'آخر ظهور'               => 'Last seen',
    'خطأ'                    => 'Error',
    'تحذير'                  => 'Warning',
    'عادي'                   => 'Info',
    'اعرض التفاصيل الكاملة'  => 'Show full details',

    // Repeat detail
    'تفاصيل رسالة متكررة'    => 'Repeated message details',
    'رجوع للتحليل'           => 'Back to analysis',
    'الرسالة غير موجودة في النافذة المفحوصة' => 'Message not found in the scanned window',
    'جرّب توسيع النافذة — الرسالة قد تكون في جزء أقدم من الملف.' => 'Try widening the window — the message may be in an older part of the file.',
    'التكرار الكلي'          => 'Total occurrences',
    'من أصل'                 => 'out of',
    'ظهور بدون تاريخ'        => 'undated occurrence(s)',
    'السطر كامل (أول ظهور)'  => 'Full line (first occurrence)',
    'آخر ظهور (قد تختلف التفاصيل المتغيرة)' => 'Last occurrence (variable details may differ)',
    'كام مرة في فترة معينة؟' => 'How many times in a date range?',
    'احسب'                   => 'Count',
    'في الفترة'              => 'In the range',
    'من إجمالي التكرار'      => 'of all occurrences',
    'التوزيع اليومي'         => 'Daily distribution',
    'اليوم'                  => 'Day',

    // Background full-file analysis
    'تحليل الملف بالكامل'    => 'Full-file analysis',
    'تحليل الملف بالكامل (في الخلفية)' => 'Analyze the whole file (in the background)',
    'فقط (الأحدث). كل الفحص بيتم على السيرفر — لا يتم تحميل الملف عندك.' => 'only (the most recent). All scanning happens on the server — the file is never downloaded to you.',
    'أو وسّع النافذة السريعة:' => 'or widen the quick window:',
    'نتيجة تحليل الملف بالكامل' => 'Full-file analysis result',
    'اكتمل في'               => 'completed at',
    'لو الملف كبر بعدها، أعد التحليل.' => 'If the file has grown since, re-run the analysis.',
    'إعادة التحليل'          => 'Re-analyze',
    'التحليل شغال على السيرفر…' => 'Analysis is running on the server…',
    'الملف بيتفحص بالكامل على السيرفر في الخلفية — تقدر تسيب الصفحة وترجع لها، النتيجة بتتحفظ.' => 'The whole file is being scanned on the server in the background — you can leave this page and come back; the result is saved.',
    'فشل التحليل:'           => 'Analysis failed:',
    'يبدو أن التحليل توقف (لا يوجد تقدم منذ أكثر من دقيقتين).' => 'The analysis appears to have stopped (no progress for over two minutes).',
    'إعادة المحاولة'         => 'Retry',

    // Server monitor
    'السيرفر'                => 'Server',
    'شغال منذ'               => 'Up for',
    'عملية نشطة'             => 'running processes',
    'تحديث تلقائي (كل 5 ثواني)' => 'Auto-refresh (every 5s)',
    'إيقاف التحديث التلقائي' => 'Stop auto-refresh',
    'كور'                    => 'core(s)',
    'نسبةً لعدد الكورات:'    => 'relative to core count:',
    'الذاكرة'                => 'Memory',
    'متاح:'                  => 'Available:',
    'كاش:'                   => 'Cache:',
    'استهلاك كل كور'         => 'Per-core usage',
    'مساحة السيرفر (البارتشنات)' => 'Server storage (partitions)',
    'نقطة التركيب'           => 'Mount point',
    'الجهاز'                 => 'Device',
    'النظام'                 => 'Filesystem',
    'مستخدم'                 => 'Used',
    'متاح'                   => 'Free',
    'الاستخدام'              => 'Usage',
    'أعلى العمليات'          => 'Top processes',
    'الحالة'                 => 'State',
    'المدة'                  => 'Elapsed',
    'الأمر'                  => 'Command',

    // Cleanup
    'تنظيف اللوجات'          => 'Log cleanup',
    'تنظيف اللوجات — حذف السطور القديمة' => 'Log cleanup — delete old lines',
    'احذف كل السطور الأقدم من تاريخ' => 'Delete all lines older than a date',
    'يتم حذف السطور التي تاريخها <strong>قبل</strong> اليوم المحدد (اليوم المحدد نفسه يبقى). السطور بدون تاريخ — مثل تكملة Stack Trace — تتبع آخر سطر مؤرَّخ قبلها.' => 'Lines dated <strong>before</strong> the chosen day are deleted (the chosen day itself is kept). Undated lines — like stack-trace continuations — follow the last dated line above them.',
    'كل الملفات'             => 'All files',
    'معاينة'                 => 'Preview',
    'اختصارات — أقدم من:'    => 'Shortcuts — older than:',
    'أسبوع'                  => '1 week',
    'شهر واحد'               => '1 month',
    '3 شهور'                 => '3 months',
    '6 شهور'                 => '6 months',
    'سنة واحدة'              => '1 year',
    'الاختصار يملأ التاريخ فقط — المعاينة تبدأ بزرار «معاينة».' => 'Shortcuts only fill the date — nothing runs until you press "Preview".',
    'تم تخطي'                => 'Skipped',
    'لا توجد سطور أقدم من'   => 'No lines older than',
    'لا شيء للحذف في هذا الملف.' => 'Nothing to delete in this file.',
    'لا شيء للحذف في الملفات المحددة.' => 'Nothing to delete in the selected files.',
    'تحذير:'                 => 'Warning:',
    'الحذف نهائي ولا يمكن التراجع عنه. سيتم حذف' => 'Deletion is permanent and cannot be undone. This will delete',
    'الأقدم من'              => 'older than',
    'سطور ستُحذف'            => 'Lines to delete',
    'حجم سيتوفر'             => 'Space to free',
    'أقدم تاريخ'             => 'Oldest date',
    'أحدث تاريخ'             => 'Newest date',
    'لا توجد صلاحية كتابة'   => 'No write permission',
    'لا توجد تواريخ متعرَّف عليها' => 'No recognizable dates',
    'تأكيد الحذف'            => 'Confirm deletion',
    'أعد إدخال التاريخ'      => 'Re-enter the date',
    'للتأكيد:'               => 'to confirm:',
    'سطر نهائيًا'            => 'line(s) permanently',
    'سيُسجَّل هذا الإجراء في سجل النشاط باسمك' => 'This action will be recorded in the activity log under your name',
    'آخر تأكيد: سيتم حذف السطور نهائيًا.' => 'Final confirmation: the lines will be permanently deleted.',
    'سيتم حذف %s سطر نهائيًا من %d ملف (الأقدم من %s). لا يمكن التراجع عن هذه العملية.' => '%s line(s) will be permanently deleted from %d file(s) (older than %s). This cannot be undone.',
    'تأكيد العملية'          => 'Confirm this action',
    'نعم، نفّذ'              => 'Yes, proceed',
    'إلغاء'                  => 'Cancel',
    'صيغة التاريخ غير صحيحة.' => 'Invalid date format.',
    'الملف المطلوب غير موجود أو خارج مجلد اللوجات.' => 'The requested file does not exist or is outside the log folder.',
    'تأكيد التاريخ غير مطابق. أعد المحاولة.' => 'Date confirmation does not match. Try again.',
    'حذف السطور الأقدم من %s: تم حذف %s سطر (%s) من %d ملف.%s' => 'Deleted lines older than %s: removed %s line(s) (%s) from %d file(s).%s',
    'حذف السطور الأقدم من'   => 'Deleted lines older than',
    'فشل:'                   => 'Failed:',
    'مسار غير صالح أو خارج مجلد اللوجات' => 'Invalid path or outside the log folder',
    'تعذّر فتح الملف'        => 'Could not open the file',
    'الملف مقفول من عملية أخرى' => 'File is locked by another process',
    'فشل الحذف على مستوى نظام الملفات' => 'Deletion failed at the filesystem level',

    // Settings
    'مسارات اللوجات وطريقة قراءتها.' => 'Log paths and how they are read.',
    'مسارات اللوجات'         => 'Log paths',
    'لكل مسار اسم يظهر في اللوحة. المسار لازم يكون مطلقًا ومقروءًا من مستخدم PHP' => 'Each path has a name shown in the dashboard. The path must be absolute and readable by the PHP user',
    '، وقابلًا للكتابة لو عايز الحذف يعمل.' => ', and writable if you want deletion to work.',
    'علّم ✕ على أي مسار لحذفه من القائمة (لا يحذف ملفاته).' => 'Tick ✕ next to a path to remove it from the list (its files are not deleted).',
    'صالح'                   => 'Valid',
    'قراءة فقط'              => 'Read-only',
    'غير صالح'               => 'Invalid',
    'حذف من القائمة'         => 'Remove from list',
    'اسم مسار جديد'          => 'New path name',
    'مسار آخر'               => 'Another path',
    'أنماط الملفات'          => 'File patterns',
    'مفصولة بفاصلة. مثال:'   => 'Comma-separated. Example:',
    'اتركها فارغة لعرض كل الملفات.' => 'Leave empty to show all files.',
    'البحث في المجلدات الفرعية' => 'Search subfolders',
    'عدد الأسطر الافتراضي عند العرض' => 'Default number of lines when viewing',
    'أقصى حجم للعرض (ميجابايت)' => 'Max view size (MB)',
    'الملفات الأكبر تُعرض جزئيًا فقط.' => 'Larger files are shown partially only.',
    'حفظ الإعدادات'          => 'Save settings',
    'معلومات النظام'         => 'System info',
    'مستخدم PHP'             => 'PHP user',
    'إصدار PHP'              => 'PHP version',
    'مجلد البيانات'          => 'Data folder',
    'قابل للكتابة'           => 'writable',
    'غير قابل للكتابة'       => 'not writable',
    'حجم سجل النشاط'         => 'Activity log size',
    'المنطقة الزمنية'        => 'Timezone',
    'تم حفظ الإعدادات.'      => 'Settings saved.',
    'تعذّر كتابة ملف الإعدادات. تأكد من صلاحيات مجلد data/.' => 'Could not write the settings file. Check the data/ folder permissions.',
    'كل مسار لازم يكون له اسم ومسار معًا:' => 'Each entry needs both a name and a path:',
    'الاسم أطول من 40 حرفًا:' => 'Name is longer than 40 characters:',
    'الاسم مكرر:'            => 'Duplicate name:',
    'المسار غير موجود أو ليس مجلدًا:' => 'Path does not exist or is not a folder:',
    'لا توجد صلاحية قراءة على:' => 'No read permission on:',
    'لم يتم تحديد أي مسار لوجات بعد. اذهب إلى الإعدادات.' => 'No log path configured yet. Go to settings.',
    'مسار «%s» غير موجود: %s' => 'Path "%s" does not exist: %s',
    'مسار «%s» ليس مجلدًا: %s' => 'Path "%s" is not a folder: %s',
    'لا توجد صلاحية قراءة على مسار «%s»: %s' => 'No read permission on path "%s": %s',
    'المجلد للقراءة فقط — الحذف لن يعمل.' => 'The folder is read-only — deletion will not work.',

    // Audit
    'كل عمليات المستخدمين — من فعل ماذا ومتى.' => 'All user operations — who did what and when.',
    'سجل نشاطك الشخصي.'      => 'Your personal activity log.',
    'إجمالي'                 => 'Total',
    'عملية.'                 => 'operation(s).',
    'ملخص الحذف لكل مستخدم'  => 'Deletion summary per user',
    'ملفات محذوفة'           => 'Files deleted',
    'حجم محرَّر'             => 'Space freed',
    'عمليات'                 => 'Operations',
    'آخر عملية'              => 'Last operation',
    'تفاصيل'                 => 'Details',
    'كل المستخدمين'          => 'All users',
    'كل الإجراءات'           => 'All actions',
    'من'                     => 'From',
    'إلى'                    => 'To',
    'ابحث في التفاصيل…'      => 'Search details…',
    'تصفية'                  => 'Filter',
    'مسح'                    => 'Clear',
    'لا توجد سجلات مطابقة'   => 'No matching records',
    'جرّب توسيع نطاق التصفية.' => 'Try widening the filter.',
    'الوقت'                  => 'Time',
    'المستخدم'               => 'User',
    'الإجراء'                => 'Action',
    'التفاصيل'               => 'Details',
    'تعديل إعدادات اللوحة'   => 'Dashboard settings changed',
    'عرض الملفات'            => 'Show files',
    'السابق'                 => 'Previous',
    'التالي'                 => 'Next',
    'صفحة'                   => 'Page',
    'الصفحة غير موجودة.'     => 'Page not found.',

    // Audit action labels
    'تسجيل دخول'             => 'Sign in',
    'محاولة دخول فاشلة'      => 'Failed sign-in',
    'تسجيل خروج'             => 'Sign out',
    'عرض ملف'                => 'View file',
    'تحليل تكرار'            => 'Repeat analysis',
    'تحميل ملف'              => 'Download file',
    'حذف ملف'                => 'Delete file',
    'تعديل الإعدادات'        => 'Settings change',
    'حذف مستخدم'             => 'User deleted',
    // 'إضافة مستخدم' and 'تغيير كلمة المرور' are defined above and shared
    // between the users page and the audit action labels.
];
